# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules =
    [ "ata_piix" "uhci_hcd" "ehci_pci" "nvme" "sr_mod" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5fb149e7-8b75-488a-aef2-ff38a6afed32";
    fsType = "ext4";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/41f61340-b8eb-477c-a22d-167a40a43a0e"; }];

  nix.maxJobs = lib.mkDefault 1;
}
